[package]
name = "axo-pass-ffi"
version.workspace = true
edition.workspace = true
description = "UniFFI bindings for axo-pass (Swift)"
publish = false

[lib]
crate-type = ["staticlib"]
name = "axo_pass_ffi"

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"

[dependencies]
anyhow.workspace = true
async-trait = "0.1"
axo-pass-core.workspace = true
log.workspace = true
secrecy.workspace = true
thiserror.workspace = true
tokio.workspace = true
uniffi = { version = "0.32", features = ["cli", "tokio"] }
uuid = "1.26.0"
