#!/bin/sh
# This script executes the axo-pass binary with the help flag if
# no args are provided, so that it doesn't open the GUI by default.
if [ $# -eq 0 ]; then
  exec "$(dirname "$0")/../MacOS/axo-pass" --help
else
  exec "$(dirname "$0")/../MacOS/axo-pass" "$@"
fi
