/*
 Generated by typeshare 1.13.3
*/

export interface AddCredentialRequest {
  vault_key: string;
  item_key: string;
  credential_title: string;
  credential_key: string;
  credential_value: string;
}

export interface AddItemRequest {
  vault_key: string;
  item_title: string;
  item_key: string;
}

export interface AppSettingsResponse {
  helper_bin_path?: string;
  vaults_dir: string;
}

export interface CredentialUpdate {
  title?: string;
  value?: string;
}

export interface DecryptedCredential {
  title?: string;
  secret: string;
  url: string;
}

export interface DecryptedCredentialRequest {
  vault_key: string;
  item_key: string;
  credential_key: string;
}

export interface DeleteCredentialRequest {
  vault_key: string;
  item_key: string;
  credential_key: string;
}

export interface DeleteItemRequest {
  vault_key: string;
  item_key: string;
}

export interface DeleteVaultRequest {
  vault_key: string;
}

export interface GetVaultRequest {
  vault_key?: string;
}

export interface VaultInfo {
  name?: string;
  key: string;
}

export interface ListVaultsResponse {
  vaults: VaultInfo[];
}

export interface NewVaultRequest {
  vault_name?: string;
  vault_key: string;
}

export interface UpdateCheckDisabledStatusResponse {
  disabled: boolean;
}

export interface UpdateItemRequest {
  vault_key: string;
  item_key: string;
  item_title: string;
  credentials: Record<string, CredentialUpdate>;
}

export interface UpdateVaultRequest {
  vault_key: string;
  new_vault_key?: string;
  new_name?: string;
}

export interface VaultItemCredentialSchema {
  id: string;
  title?: string;
}

export interface VaultItemSchema {
  id: string;
  title: string;
  credentials: Record<string, VaultItemCredentialSchema>;
}

export interface VaultSchema {
  key: string;
  name?: string;
  path: string;
  data: Record<string, VaultItemSchema>;
}

export interface VaultResponse {
  vault: VaultSchema;
}

export type UpdateStatusResponse =
  | {
      status: 'update_available';
      data: {
        version: string;
        checked_at_rfc3339: string;
      };
    }
  | {
      status: 'up_to_date';
      data: {
        version: string;
        checked_at_rfc3339: string;
      };
    }
  | {
      status: 'error';
      data: {
        error: string;
        checked_at_rfc3339: string;
      };
    }
  | {status: 'not_checked'; data?: undefined};
